### ISSUE TITLE
Wallet recovery view bug

### ISSUE THREAD

**Issue by macsleven** [raedahgroup/dcrios#319]
- if you have a text box selected for input, and sleep/wake cycle the device, it scrunches up all content at the very top, and if you do it again, it removes everything from view
- Keyboard should dismiss when tapped outside its view
<img src="https://i.imgur.com/30K5adY.png" width="300">

**Comment by jrick** [comment]
The keyboard issue is actually more complicated to properly fix than simply hiding it.  It should never cover app content.  The app is made aware of when the keyboard is in view, and how large it is, and should be resized as the keyboard is shown/hidden so that content is never covered by it.  I believe this is fundamentally different to how android apps handle keyboards, as they are not aware of whether a keyboard is being shown or not.
